[project]
name = "app-manager"
version = "0.0.1"
description = "App manager entrypoint"
requires-python = ">=3.10"
dependencies = [
    "wexample-wex-addon-dev-javascript==0.0.55",
]

[tool.pdm]
distribution = false
